# Generated by Django 4.2.19 on 2025-03-17 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_role', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='leaveapplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_id', models.CharField(max_length=20)),
                ('employee_name', models.CharField(max_length=100)),
                ('leave_description', models.TextField()),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_role.department')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_role.leave')),
            ],
        ),
    ]
