# Generated by Django 4.2.19 on 2025-03-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_role', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
