# Generated by Django 4.2.19 on 2025-03-24 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_role', '0002_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='end',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='title',
            new_name='section_name',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='start',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='description',
        ),
    ]
