# Generated by Django 4.2.19 on 2025-03-27 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_role', '0003_rename_end_schedule_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='admin_role.faculty'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_replacement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedule',
            name='replaced_faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacements', to='admin_role.faculty'),
        ),
    ]
