from django.urls import path
from . import views

urlpatterns = [
    path('index/', views.index, name='index'),
    path('faculties/', views.faculties, name='faculties'),
    path('add_faculty/', views.add_faculty, name='add_faculty'),
    path('delete_faculty/<int:pk>', views.delete_faculty, name='delete_faculty'),
    path('edit_faculty/<int:pk>', views.edit_faculty, name='edit_faculty'),  
    path('hod/', views.hods, name='hods'),
    path('add_hod/', views.add_hod, name='add_hod'),
    path('delete_hod/<int:pk>', views.delete_hod, name='delete_hod'),
    path('edit_hod/<int:pk>', views.edit_hod, name='edit_hod'),
    path('departments/', views.departments, name='departments'),
    path('add_department/', views.add_department, name='add_department'),
    path('delete_department/<int:pk>', views.delete_department, name='delete_department'),
    path('edit_department/<int:pk>', views.edit_department, name='edit_department'),
    # path('subjects/', views.subjects, name='subjects'),
    # path('subjects/<int:department_id>/', views.subjects, name='subjects_by_department'),
    # path('add_subject/', views.add_subject, name='add_subject'),
    # path('delete_subject/<int:pk>', views.delete_subject, name='delete_subject'),
    # path('edit_subject/<int:pk>', views.edit_subject, name='edit_subject'),
    path('schedules_list/', views.schedules_list, name='schedules_list'),
    path('schedules/<int:faculty_id>/', views.schedules, name='schedules'),
    path('api/schedules/<int:faculty_id>/', views.get_schedules, name='get_schedules'),
    path('api/active_leaves/<int:faculty_id>/', views.get_active_leaves, name='get_active_leaves'),
    path('api/create_schedule/', views.create_schedule, name='create_schedule'),
    path('api/update_schedule/', views.update_schedule, name='update_schedule'),
    path('api/delete_schedule/', views.delete_schedule, name='delete_schedule'),
    path('api/create_replacement/', views.create_replacement, name='create_replacement'),
    path('clear_schedules/<int:faculty_id>/', views.clear_schedules, name='clear_schedules'),
    path('leave_types/', views.leaves, name='leaves'),
    path('add_leave/', views.add_leave, name='add_leave'),
    path('delete_leave/<int:pk>', views.delete_leave, name='delete_leave'),
    path('edit_leave/<int:pk>', views.edit_leave, name='edit_leave'),
    path('api/allocate_replacements/', views.allocate_replacements, name='allocate_replacements'),
    path('leave_applications/', views.leave_applications, name='leave_applications'),
    path('api/update_leave_status/<int:pk>/', views.update_leave_status, name='update_leave_status'),
]